version: "3"
services:
  centos:
    container_name: "wordPress"
    image: centos
    tty: true
    ports:
      - "127.0.0.1:8080:80"
    privileged: true
    command: /sbin/init
    environment:
      TZ: Asia/Tokyo
